#ifndef GUARD_CONSTANTS_BATTLE_MODE_H
#define GUARD_CONSTANTS_BATTLE_MODE_H

#define BATTLE_MODE_SINGLES 0
#define BATTLE_MODE_DOUBLES 1
#define BATTLE_MODE_MIXED   2

#endif // GUARD_CONSTANTS_BATTLE_MODE_H
